<a href="https://colab.research.google.com/github/polamsumanth/B3_PFDS_1121/blob/main/NUMPY_CONCEPTS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY

In [8]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
b = np.array([[1,2],[3,4]])
print(b)
c = np.zeros((2,2))
print(c)
d = np.ones((2,3))
print(d)
print('Done')

[1 2 3 4]
[[1 2]
 [3 4]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
Done


RANGE OF NUMBERS

In [9]:
range_arr = np.array([0,10,2])
print("Range Array: ", range_arr)

Range Array:  [ 0 10  2]


RANDOM ARRAY

In [12]:
rand_arr = np.random.rand(2,3)
print("Random Array:\n", rand_arr)

Random Array:
 [[0.31386736 0.9050332  0.34348727]
 [0.95470557 0.58870002 0.41953713]]


ATTRIBUTES

In [15]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.size)
print(a.itemsize)

(2, 3)
2
int64
6
8


ARRAY INDEXING AND SLICING

In [17]:
a = np.array([10,20,30,40])
print(a[2])
print(a[3])
print(a[-1])
print(a[1:3])
print(a[::2])
print(a[1::])

30
40
40
[20 30]
[10 30]
[20 30 40]


2D ARRAY

In [19]:
a = np.array([[10,20,30], [40,50,60]])
print(a[1][1])
print(a[0:1])
print(a[1:])
print(a[::1])

50
[[10 20 30]]
[[40 50 60]]
[[10 20 30]
 [40 50 60]]


ARITHEMATIC OPERATIONS

In [20]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a**b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[  1  32 729]
[0.25 0.4  0.5 ]


AGGREGATE FUNCTIONS

In [23]:
a = np.array([[1,2,3],[4,5,6]])
print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.mean(a))
print(np.std(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

21
6
1
6
3.5
1.707825127659933
[5 7 9]
[ 6 15]


BROAD CASTING

In [24]:
a = np.array([1,2,3])
b = 5
print(a+b)
print(a*b)

[6 7 8]
[ 5 10 15]
